### PR TITLE
ldk7811 contribution

### PR DESCRIPTION
**Pull request by ldk7811**

### CODE REVIEW

**Comment by MoralCode** [comment]
Looks good! It might be nice to update the title of your post (you can use the `title` attribute at the top of the file to avoid renaming the file) to summarize what your contribution was (especially since your name is already in the authorship field of the post), but this is just a suggestion. It seems like everything at least works.

Will wait for you to let me know if you want to make this edit or if you want me to merge this

**Comment by MoralCode** [comment]
its been a few days and the due date is probably coming up soon if hasnt already passed. Merging

**Comment by MoralCode** [comment]
@ldk7811 of course only after merging do i realize i had a question lol.

Did you intend to submit this as your contribution or as your bug fix?  It's showing up on the site under the Contributions category:
Screenshot_20240407_112006

**Comment by ldk7811** [comment]
It's a contribution

**Pull request merged**
