### PR TITLE
Karl Choi - Bug Fix 1 Post

### PR DESCRIPTION
**Pull request by kc6827**
Project: Dark Reader

### CODE REVIEW

**Comment by MoralCode** [comment]
Looking pretty good!

Just wanted to check to see if this was how you intended to have the images laid out since it seems like you used several small images and I know the markdown renderer can try to be clever sometimes and end up messing things up.  I assume since you tested this with a GitHub pages site on your fork (it helps a lot when reviewing the PRs!) this is probably as intended but figured I'd double check anyways

Screenshot_20240409_151023

**Comment by kc6827** [comment]
Sorry about that
It should be fixed now

**Comment by MoralCode** [comment]
Screenshot_20240411_141448

They still seem a little smushed together, but i may just be being pedantic since its a fairly minor thing - up to you whether you want to keep trying or if i should just merge it.

Also i suspect since your images are coming from discord, they're [probably going to expire eventually](https://www.bitdefender.com/blog/hotforsecurity/discord-tightens-security-with-temporary-file-links/), so it may be ideal to add the image files themselves to this repo (you're welcome to copy what some other students in class have done with their images).

**Comment by kc6827** [comment]
I think it's good to be merged
thanks

**Comment by CodingArctic** [comment]
fyi the img links broke like adrian said they would, lol

**Comment by MoralCode** [comment]
ah yeah i knew there was at least one other post that was hotlinking images from discord.

@kc6827 please include your images as files in the repo, or upload them to a more reliable image hosting service so that I can grade your blog post. ~20% of the grade is based on your use of images

**Comment by kc6827** [comment]
Hi @MoralCode, I created a new pull request. Thanks for letting me know about the issue.

**Pull request merged**
